<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;
use yii\validators\StringValidator;
/**
 * This is the base-model class for table "user_details".
 *
 * @property integer $id
 * @property integer $user_id
 * @property string $name
 * @property string $mobile
 * @property string $profile_image
 * @property integer $city_id
 * @property string $street_address
 * @property string $zip
 * @property string $lat
 * @property string $lng
 * @property string $suburb
 *
 * @property \app\models\User $user
 * @property \app\models\City $city
 * @property string $aliasModel
 */
abstract class UserDetails extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'user_details';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
             ['zip', 'string', 'length' => 5],
            [['user_id','name', 'mobile', 'city_id', 'street_address', 'zip'], 'required'],
            [['user_id', 'city_id','mobile','zip'], 'integer'],
            [['name',  'profile_image', 'street_address', 'lat', 'lng', 'suburb'], 'string', 'max' => 255],
            
            
            [['user_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\User::className(), 'targetAttribute' => ['user_id' => 'id']],
            [['city_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\City::className(), 'targetAttribute' => ['city_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('models', 'ID'),
            'user_id' => Yii::t('models', 'User ID'),
            'name' => Yii::t('models', 'Name'),
            'mobile' => Yii::t('models', 'Mobile'),
            'profile_image' => Yii::t('models', 'Profile Image'),
            'city_id' => Yii::t('models', 'City ID'),
            'street_address' => Yii::t('models', 'Street Address'),
            'zip' => Yii::t('models', 'Zip'),
            'lat' => Yii::t('models', 'Lat'),
            'lng' => Yii::t('models', 'Lng'),
            'suburb' => Yii::t('models', 'Suburb'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getUser()
    {
        return $this->hasOne(\app\models\User::className(), ['id' => 'user_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCity()
    {
        return $this->hasOne(\app\models\City::className(), ['id' => 'city_id']);
    }


    
    /**
     * @inheritdoc
     * @return \app\models\UserDetailsQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \app\models\UserDetailsQuery(get_called_class());
    }


}
